version: "3.3"

services:
  whalefisher:
    # beta 6 exposes just a flask route
    # beta 8 correctly exposes json routes - logs undefined
    # beta 13.2 streams out logs - but stuck endpoint
    # beta 16 return jsonified list (compact view)
    # beta 16.1 returns json {name:, linenr:}
    # beta 16.2 strict slashes=False
    # beta 16.3 keep both behaviours in diff urls
    # beta 16.6 tasks with desired: running
    # beta 17.2 decorate client as resource, client info
    # 0.2 as 17.2
    # 0.2.1 include new setup.py version
    # 0.2.1.1 test other log than self - occasional timeout still exists on all urls as well (not only logs),
    # solution: may need to remove ::1     localhost ip6-localhost ip6-loopback from /etc/hosts
    # 0.2.3 include node labels, availability
    # 0.2.4 Add tasks by service name
    # 0.2.4.1 Add service route
    # 0.2.5 Add get tasks by service name route, 0.2.5.1 fix
    # 0.2.5.2 Return empty task list
    # 0.2.6 Refine search services by name, tasks
    # 0.2.6.1 Fix list routes
    # 0.2.6.2 Add active node by getting environ['DOCKER_NODE']
    # 0.2.7 Fix route to current nodename
    # 0.2.7.1 Add Requests module

    # 0.3 or 0.4 Import pyld (setup.py) ,from pyld import jsonld, to implement HateOas
    image: registry.dream:5001/whalefisher:0.2.7.1
    deploy:
      replicas: 1
    environment:
      - DOCKER_NODE={{.Node.Hostname}}
    ports:
      - "80:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock