version: "3.3"

services:
  whalefisher:
    # beta 6 exposes just a flask route
    # beta 8 correctly exposes json routes - logs undefined
    # beta 13.2 streams out logs - but stuck endpoint
    # beta 16 return jsonified list (compact view)
    # beta 16.1 returns json {name:, linenr:}
    # beta 16.2 strict slashes=False
    # beta 16.3 keep both behaviours in diff urls
    # beta 16.6 tasks with desired: running
    # beta 17.2 decorate client as resource, client info
    # 0.2 as 17.2
    # 0.2.1 include new setup.py version
    # 0.2.1.1 test other log than self
    image: registry.dream:5001/whalefisher:0.1-beta16.3
    deploy:
      replicas: 1
    ports:
      - "80:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock